- BottomWidgets/BottomWidget.cpp
- BottomWidgets/BottomWidget.h
- Entities/MusicPlayer/musicPlayer.cpp
你好，我做了一些修改。
尝试修复的问题：
<br>
1. 播放时拖动 sliderSong 进行 seek 后，如果时间正好，sliderSong 会跳回当前播放的位置：
https://github.com/BensonLaur/Beslyric-for-X/blob/81d51042e3e1273faeaca3002eb3f92cbd2b227e/Entities/MusicPlayer/musicPlayer.cpp#L891-L902
<br>
<br>
1. 暂停时拖动 sliderSong 进行 seek 后会继续播放音乐，但 btnPlayAndPause 的样式并不会由“播放”变为“暂停”；
2. 音乐播放结束后 btnPlayAndPause 的样式不会由“暂停”变为“播放”；
3. btnPlayAndPause 的样式现在由 musicPlayer 发出的信号决定，而不是在切换状态的时直接修改：
https://github.com/BensonLaur/Beslyric-for-X/blob/81d51042e3e1273faeaca3002eb3f92cbd2b227e/BottomWidgets/BottomWidget.cpp#L157-L160
https://github.com/BensonLaur/Beslyric-for-X/blob/81d51042e3e1273faeaca3002eb3f92cbd2b227e/BottomWidgets/BottomWidget.cpp#L169
<br>
<br>
1. PlayThread 在进行 Seek 前后对音乐进行暂停和播放没有发出相应的信号：
https://github.com/BensonLaur/Beslyric-for-X/blob/81d51042e3e1273faeac …
> 关于播放条、播放控制按钮在拖动后、音乐播放结束后的修复

- BesWidgets/table/BesNcmSongTableView.cpp
- Entities/LyricSearcherFactory/ThreadSearchNcmMusic.h
- Entities/SettingManager.cpp
- Entities/SettingManager.h
- Entities/SkinFactory/ISkin.h
- Entities/ThreadGuessLyricInfo.h
- MiddleWidgets/SettingWidget/SuMusicDownload.cpp
- MiddleWidgets/SettingWidget/SuMusicDownload.h
- MiddleWidgets/SubPageDownloadLyric.cpp
- MiddleWidgets/SubPageDownloadLyric.h
- MiddleWidgets/SubPageDownloadSong.cpp
1、实现 issue #9 希望支持切换文件名命名格式 功能，支持"歌手 - 歌曲名"|“"歌曲名 - 歌手" 2 种命名方式的切换
2、修复"下载歌词"页面"LRC歌词"面板中"选择“"和"保存LRC歌词"失效问题
> 支持"歌手 - 歌曲名"|“"歌曲名 - 歌手" 2 种命名方式保存文件；修复"下载歌词"页面按钮失效问题

- BottomWidgets/BottomWidget.cpp
- BottomWidgets/BottomWidget.h
- Entities/MusicPlayer/musicPlayer.cpp
- Entities/MusicPlayer/musicPlayer.h
对 #13 中提到的部分问题的修复，在 BottomWidget::onSliderSongPressed()、BottomWidget::onSliderSongMoved(int) 和 BottomWidget::onSliderSongReleased() 三个方法中进行了修改：
1. 不播放任何歌曲，拖动并释放 sliderSong 会执行 musicPlayer->seek(posAdjust)：
对 AdjustingPos 的赋值和判定进行重写，AdjustingPos 的值现在由 bInMakingMode 和 musicPlayer->state() 决定，而 AdjustingPos 决定最终是否执行 musicPlayer->seek(posAdjust)；
2. 在播放时单击或长按 sliderSong（不拖动），可能会使 sliderSong 回退到之前的某个时刻：
添加成员变量 sliderSongOriginalPos 记录 sliderSong 在 BottomWidget::onSliderSongPressed() 时的位置，在 BottomWidget::onSliderSongReleased() 时将 sliderSong 的当前值与 sliderSongOriginalPos 比较，相同则不执行 musicPlayer->seek(posAdjust)；
<br>
整理的逻辑：
1. 移除 BottomWidget 中除了 onAudioFinished(bool)、onAudioPlay() 和 onAudioPause() 中的对 btnPlayAndPause 样式的修改（包括之前注释掉的），也移除了相关的判定；
2. 切换播放暂停状态的代码从 BottomWidget  移动到 …
> 修复有关播放条的问题，整理部分界面逻辑

- Entities/MP3Editor/mp3Editor.cpp
- MiddleWidgets/MiddleWidget.cpp
- MiddleWidgets/SubPageMaking.cpp
使用 QFileInfo::completeBaseName() 而不是 QFileInfo::baseName()，避免文件名在第一个“.”处结束。
https://doc.qt.io/qt-5/qfileinfo.html#completeBaseName
> 修复含有“.”的歌曲文件的文件名不能被正确识别

- Utility/Utility.pri
已在 Windows 7 / 10 和 Ubuntu 18.04 上的 Qt 5.9.8 测试。
Windows 上去掉`Qt5Network(d)` 功能正常；
Ubuntu 上**不去掉**`Qt5Network(d)`会报找不到库的错：
```
/usr/bin/ld: cannot find -lQt5Networkd
```
等待你进一步的验证。
> 移除显式指定使用 Qt5Network(d)

- StackFrame.cpp
在 Windows 10 1903 / macOS 10.15 下测试通过；
而 Ubuntu 18.04 (GNOME Shell 3.28.2) 本身具有这样的特性，本 PR 对其没有影响。
使用`QScreen->availableGeometry()`获得屏幕可用区域再做运算，而不是把 (0, 0) 作为左上角。
暂时没有考虑多屏幕的情况，所以直接使用`QGuiApplication::screens()`列表的第一个`QScreen`的指针。
> 使最大化窗口自适应屏幕可用区域

- BesWidgets/BesSlider.h
- BottomWidgets/BottomWidget.cpp
- BottomWidgets/BottomWidget.h
- Entities/MusicPlayer/musicPlayer.cpp
- Entities/MusicPlayer/musicPlayer.h
本 PR 重写了`BesSlider`和相关界面逻辑，解决了播放进度条在使用上的主要问题。本 PR 还修改了部分播放逻辑，试图让程序运行得更好（properly）。
本 PR 试图解决 #12 、 #13 、 #15 、 #16 、 #17 、 #19 、 #20 、 #21 、 #23 、 #31 、 #32 、 #38 、 #39 、 #41 和 #42 中提到或遗留的问题。
本 PR 在 Ubuntu 18.04 / Windows 10 1903 / macOS 10.15<sup><a name="id394062" href="#ftn.id394062">\[1\]</a></sup> 测试通过。
来自 #41 。
来自 #42 。
在 https://github.com/BensonLaur/Beslyric-for-X/pull/38#issuecomment-552202094 提到。
在 #23 和 #38 提到。
本 PR 对于 #23 和 #38 的解决不完全，特别是 https://github.com/BensonLaur/Beslyric-for-X/pull/38#issuecomment-554613738 提到的问题，这可能需要重新设计`PlayThread`。
对于音频是否到达尾部有更好的方法，见上文。
这部分修改是以我自己的理解来做的，目的是修 BUG，并且让逻辑更清楚。但目前我还没有掌握 FFmpeg 的基本用法，所以可能有不合理之处。
- 如果`PacketQueue`的第一个`AVPacket`包是`nullptr`，同时`block`置为`false`，那么`packet_queue_get()`将会返回`-1`。
- 除非重采样（SWR …
> 新的 BesSlider 和更好用的 MusicPlayer

- Entities/MusicPlayer/musicPlayer.cpp
相比于之前的写法，现在从点击音乐到音乐开始播放的延迟缩短了许多。
不同平台的表现：
- Ubuntu 18.04 下现象明显；
- Windows 10 1903 下没有明显改变；
- macOS 10.15 下没有明显改变。
注：之后的 PR 中，若无特别说明，所使用的 FFmpeg 版本均与 beslyric-lib 一致（例如现在为 4.0.1 ）。
> Remove SDL_INIT_TIMER and SDL_INIT_VIDEO from SDL_Init()

- Entities/MusicPlayer/musicPlayer.cpp
一些分析写在了 #39 里。
看起来`av_format.h`里的`read_header()`方法**似乎**是噪音出现的源头。
> The noise in the first two seconds disappeared.

- Entities/MusicPlayer/musicPlayer.cpp
Minor fix.
Use av_samples_get_buffer_size() to calculate the size of the buffer.
> Use calculated buffer size.

- BesWidgets/BesSlider.h
在 Qt < 5.8.0 版本中，[`QMouseEvent`](https://doc.qt.io/qt-5/qmouseevent.html)没有[`setLocalPos`](https://github.com/qt/qtbase/blob/1e654450157ca422833d48c0faf4fe0836c3125f/src/gui/kernel/qevent.cpp#L412-L422)成员方法。为了实现相同效果，构造一个新的`QMouseEvent`并让传入的参数`ev`指向它。由于新的`QMouseEvent`在栈上，所以**似乎**不用考虑内存管理的问题。
---
完整讨论：https://github.com/BensonLaur/Beslyric-for-X/pull/47#pullrequestreview-344947659
这是 78c4d786a5747bb5dd6e1c090d2911d0e637a206 的补丁。
> 在 Qt 5.8 以下版本中“实现”了 QMouseEvent::setLocalPos

- Entities/MusicPlayer/musicPlayer.cpp
Fixed #51
Patch for 0175326182c6d4e284cd23c657480e6bbf18b896
<br>
本 PR 修复的问题在 Windows 平台上似乎是不存在的：
| 操作系统 | 编译器 | FFmpeg | 是否复现 #51 |
| - | - | -:|:-:|
| Windows 10 | Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24234.1 for x86 | 4.0.1/4.2.2 | X |
| Windows 7 | Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x86 | 4.0.1/4.2.2 | X |
| Ubuntu 18.04 | gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)  | 4.2.2 | O |
| macOS 10.14 | Apple LLVM version 10.0.0 (clang-1000.10.44.4) | 4.2.2 | O |
> 避免对未成功获取（未初始化）的 AVPacket 进行释放

- Entities/MP3Editor/mp3Editor.pri
- Entities/MusicPlayer/musicPlayer.pri
在使用 MSVC v141 及以上版本时，链接报错：
```
SDL2main.lib(SDL_windows_main.obj) : error LNK2005: _main already defined in main.obj
MSVCRTD.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : warning LNK4217: symbol '_fprintf' defined in 'mp3Editor.obj' is imported by 'SDL2main.lib(SDL_windows_main.obj)' in function '_ShowError'
SDL2main.lib(SDL_windows_main.obj) : error LNK2019: unresolved external symbol _SDL_main referenced in function _main
SDL2main.lib(SDL_windows_main.obj) : error LNK2019: unresolved external symbol __imp____iob_func referenced in function _ShowError
debug\Beslyric-for-X.exe : fatal error LNK1120: 2 unresolved externals
```
分析后得出：Beslyric-for-X （以下简称 B4X ）使用[`SDL_Init(Uint32 …
> 移除对 SDL2main 库的链接

- Beslyric-for-X.pro
添加`-no-pie`标志到[`QMAKE_LFLAGS`](https://doc.qt.io/qt-5/qmake-variable-reference.html#qmake-lflags)，使 Ubuntu 认为输出的二进制文件是可执行文件而不是动态链接库（共享库、共享链接库），进而使输出文件能被双击运行，同时显示为可执行程序的图标。
| | before | after |
| - |:- |:- |
| "Properties..." | shared library (application/x-sharedlib) | executable (application/x-executable) |
| `file` | ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked | ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked |
参考：
- https://stackoverflow.com/questions/45329372/ubuntu-recognizes-executable-as-shared-library-and-wont-run-it-by-clicking
- https://forum.qt.io/topic/70710/wrong-executable-generation-in-release-mode
- https://forum.qt.io/topic/80690/solved-debian-9-qt-program-compile
- …
> 使 Ubuntu 将输出文件识别为可执行程序

- Beslyric-for-X.pro
- README.md
本 PR 拆分至 #35 ，经过 #54 的尝试，最后由 https://github.com/BensonLaur/Beslyric-for-X/pull/35#issuecomment-585542773 定好方向。
---
无论是否有`debug_and_release`或`debug_and_release_target`标志，也不管是否启用 Shadow build ，输出的文件始终都位于`$${OUT_PWD}/[ debug | release ]_bin`文件夹，方便后续的操作（例如使用 windeployqt 部署 Qt 库或使用 Inno Setup 提取文件）。
经测试，`debug_and_release_target`的作用会被`$$DESTDIR`覆盖。
---
本 PR 已在以下环境通过测试：
- Qt 5.14.1 (macOS 10.15, Windows 10 1903, Windows 10 1909, Ubuntu 18.04.3 and Ubuntu 18.04.4)
- Qt 5.13.2 (macOS 10.14)
- Qt 5.9.8 (Windows 10 1903 and Ubuntu 18.04.3)
---
一些有序或者杂乱的资料：
- [qmake Manual](https://doc.qt.io/qt-5/qmake-manual.html)
- [Undocumented QMake - Qt Wiki](https://wiki.qt.io/Undocumented_QMake)
- [Technical FAQ - Qt Wiki](https://wiki.qt.io/Technical_FAQ)
> 使用“ DESTDIR ”变量分离二进制文件

- Entities/LyricMaker.cpp
- MiddleWidgets/SubPageMaking.cpp
Fixed #65 
Reversed 8b5141f5ba94899ea2e6ae3fb235f0459abcf671
@BensonLaur @ish-kafel 
---
#65 与`curAudioPos`关系不大，故撤销上一个提交（不过，没有为`curAudioPos`赋初值的确会造成潜在的问题）。
<br>
实际上，无论是哪一句歌词，只要`insertOffsetTime`大于音频的当前播放时间，由于盲目的计算`time -= insertOffsetTime`，都会使计算出的时间戳为负值。
---
注意，**出现负值的根本原因是程序中数据类型的混乱**，代码如下：
https://github.com/Beslyric-for-X/Beslyric-for-X/blob/8b5141f5ba94899ea2e6ae3fb235f0459abcf671/Entities/LyricMaker.cpp#L319-L337
证明：
1. `quint64`类型最大值为`18446744073709551615`，`int`类型范围为`-2147483648`到`2147483647`，共`4294967296`个数；
2. 在`18446744073709551615`进行两次除法运算（分别除以`1000`和`60`）后，值为`307445734561825`；
3. 通过取模（这里也可以称为取余，因为同号）运算`307445734561825 % 4294967296`，值为`3385579553`，即对于`unsigned int`类型，结果为`3385579553`；
4. 由于输出时转换为`int`类型（`%.2d`），又因为`3385579553`>`2147483647`，所以结果为负数；
5. `3385579553 - …
> 避免大于音频当前播放时间的“提前毫秒数”使歌词时间戳为负

- Entities/MusicPlayer/musicPlayer.cpp
Fixed #37
---
原因：
- 在 macOS 10.14+ 进行 seek 或重新播放时，`pkt1`为`null`；
- 这个`if`语句没有实际作用。
> 注释对 AVPacket 的无用测试以避免段错误

- BesWidgets/table/FinishLrcTableModel.h
- BesWidgets/table/FinishLrcTableView.cpp
- BesWidgets/table/FinishLrcTableView.h
- BottomWidgets/BottomWidget.cpp
- BottomWidgets/BottomWidget.h
- Entities/LyricMaker.cpp
- Entities/LyricMaker.h
- Entities/MusicPlayer/musicPlayer.cpp
- Entities/MusicPlayer/musicPlayer.h
- MiddleWidgets/LyricEditorBox.cpp
- MiddleWidgets/LyricEditorBox.h
- MiddleWidgets/SubPageMaking.cpp
- MiddleWidgets/SubPageMaking.h
1、为了消除 MusicPlayer::backwardSeek(quint64 step) 中有/无符号数不匹配的 warning , 调整使用的类型
2、参考 ffmpeg 代码，时间都是使用 int64_t 所以决定程序中所有 quint64 改为 qint64
> 消除时间相关存储类型不一致导致的 warning

- MiddleWidgets/MiddleWidget.cpp
- MiddleWidgets/SettingWidget/SettingScrollPanel.cpp
- MiddleWidgets/SettingWidget/SettingScrollPanel.h
- MiddleWidgets/SettingWidget/SuDefaultPath.cpp
- MiddleWidgets/SettingWidget/SuDefaultPath.h
- MiddleWidgets/SubPageDownloadLyric.cpp
- MiddleWidgets/SubPageDownloadLyric.h
- MiddleWidgets/SubPageMaking.cpp
- MiddleWidgets/SubPageMaking.h
resolves #75
1、默认“歌词目录” 改变，需要立刻同步改变 “下载歌词->原歌词” 页面下的 edit 控件
2、默认“输出目录” 改变，需要立刻同步改变 “制作歌词” 页面下的输出目录 edit 控件
以及 “下载歌词->LRC歌词” 页面下的 edit 控件
> 使默认目录更改立刻生效

- Entities/MP3Editor/mp3Editor.h
The compiler said, "Suggest braces around initialization of subobject."
GCC 5 said, "could not convert `(void*)foo` from `void*` to `OptionDef::<anonymous union>`."
---
Tested on: GCC 5.4.0 / 7.4.0, MSVC 2015 / 2019 and Apple Clang 11.0 .
> 为子对象的初始化添加大括号以通过 GCC 5 的静态检查

- BesWidgets/table/BesNcmSongTableView.cpp
- MiddleWidgets/SubPageDownloadLyric.cpp
修复保存歌曲和歌词时，名称中含有“/”等windows不支持的特殊符号导致的保存失败问题
> 修复文件名称含有特殊字符时保存失败问题

- Entities/MusicPlayer/musicPlayer.cpp
> 检查 swr_init() 的返回值以避免参数错误使程序崩溃

- BesWidgets/table/BesNcmSongTableView.cpp
- MiddleWidgets/SubPageDownloadLyric.cpp
Windows 系统中规定文件名称不能包含字符 /\|*?<>:"
所以这里在需要保存文件（歌曲、歌词）前，将文件名中的以上字符替换为下划线 "_"
fix issue #91
Note: this is a Redo of #103 (simply just for testing reason)
> （Redo）修复文件名称含特殊字符时保存失败问题

- Entities/LyricListManager.cpp
- Entities/SettingManager.cpp
Fix #59 .
Fix #88 .
现在使用 [`QStandardPaths`](https://doc.qt.io/qt-5/qstandardpaths.html)`::AppLocalDataLocation` 这个路径，数据文件将会位于如下位置：
| OS | Path |
|:- |:- |
| Windows | `%LOCALAPPDATA%/<APPNAME>` (`C:/Users/<USER>/AppData/Local/<APPNAME>`) |
| macOS | `~/Library/Application Support/<APPNAME>` |
| Linux | `~/.local/share/<APPNAME>` |
<br>
注意，程序关于配置和歌单的存储逻辑仍然有改进的空间。
> 使用新的数据文件路径以解决权限问题

- Beslyric-for-X.pro
- Entities/MP3Editor/ffmpegDefine.h
- Entities/MusicPlayer/musicPlayer.h
本 PR 由 #117 修改而来。
---
为了正确处理依赖，在 Windows 上需要设置环境变量 `B4X_DEP_PATH`。
各个 64 位平台的文档：
- Linux: https://github.com/BesLyric-for-X/BesLyric-for-X_Conf/tree/linux_x64_3.1.3
- macOS: https://github.com/BesLyric-for-X/BesLyric-for-X_Conf/tree/macos_x64_3.1.3_1
- Windows: https://github.com/BesLyric-for-X/BesLyric-for-X_Conf/tree/windows_x64_3.1.3
---
关于 SDL2main 和 SDL_MAIN_HANDLED ： https://github.com/BesLyric-for-X/BesLyric-for-X/pull/53#issuecomment-769120183
> ! 新的依赖指令 2

- Entities/LyricMaker.cpp
> 输出的时间标签格式由3位小数位调整为2位小数位

- Entities/ThreadLogin.h
Fix 837005372d431e07e4b4f0911469cecc9bff4b15 in #119 .
> ## QUrlQuery::QUrlQuery(std::initializer_list<QPair<QString, QString> > list)
> Constructs a QUrlQuery object from the list of key/value pair.
> 
> This function was introduced in Qt 5.13.
> https://doc.qt.io/qt-5/qurlquery.html#QUrlQuery-3
我的错。
> 不在 Qt 5.12 及更低版本中使用未引入的 QUrlQuery 的列表初始化构造方法

- Beslyric-for-X.pro
- MiddleWidgets/SettingWidget/SuUpgrade.cpp
- MiddleWidgets/SettingWidget/SuUpgrade.h
- StackFrame.cpp
- StackFrame.h
用于 CI 。
<br>
将通过两种方式输出该 SHA1 ：
- qDebug()
- BesMessageBox::information()
<br>
需要在环境中设置或向 qmake 传入 `GIT_COMMIT_SHA1=...` 才能进行构建；可以使用 `git rev-parse HEAD` 以获取该 SHA1 。
Shell or PowerShell:
```console
> qmake -before "GIT_COMMIT_SHA1=$(git rev-parse HEAD)"
```
> 程序启动时输出用于构建当前程序的源代码的 Git 提交 SHA1

- Beslyric-for-X.pro
与 #77 、 #82 中的 3cae066a7613e3aca4eff8aed0cc299b7fa25347 有关。
在 CI 上，我们仅进行 release 配置的构建，同时也需要 `qDebug()` 的输出以进行测试，所以原来的办法，即通过 `CONFIG` 判断当前是否为 release 配置来决定是否禁用 `qDebug()` ，就变得不适用。
如果不进行任何配置， `qDebug()` 是启用的；当我们需要禁用 `qDebug()` ，例如制作分发给用户的发行版时，就要通过 `qmake '-before' 'DEFINES*=RELEASE_VERSION'` 传入宏 `RELEASE_VERSION` 以禁用 `qDebug()` 。
注意，宏 `RELEASE_VERSION` 还被用于 #127 中的 1bb29f4a0895f61be4e1e33c3562d5cd766380ef 。
> 在定义了 RELEASE_VERSION 时，定义 QT_NO_DEBUG_OUTPUT 以禁用 qDebug 

- Beslyric-for-X.pro
与 #127 和 #128 有关。
为了方便开发， qmake 将不会在未获取到有效的 `GIT_COMMIT_SHA1` 或 `APP_VERSION` 时报错，而是使用默认值（全 0 ）。同时，如果 git 所在文件夹被正确配置到了 PATH 中，以上两个信息将会被自动获取。
> 自动获取 或 使用 默认的 版本号 和 Git 提交 SHA1

- Beslyric-for-X.pro
与 #123 的 f1c6b07332c8430da2dd1ab86e3cac8d4f122b99 有关。
将所有的 dll 和 lib 文件存储到文件夹 `%B4X_DEP_PATH%\lib\` 。
由于 `LIBS` 中的文件夹的路径会被添加到 Qt Creator 的“ Run Environment ”的 `PATH` 中，用户就可以直接在 Qt Creator 中运行 BesLyric-for-X 而不需要手动复制 dll 文件。
文档也更新了：
- Windows: https://github.com/BesLyric-for-X/BesLyric-for-X_Conf/tree/windows_x64_3.1.3_1
> 在 Windows 平台 将 lib 与 dll 文件放在同一个文件夹 以便在 Qt Creator 中调试

- .gitignore
来自 https://github.com/github/gitignore/blob/218a941be92679ce67d0484547e3e142b2f5f6f0/Global/VisualStudioCode.gitignore 。
> 添加 VS Code 的 .gitignore

- main.cpp
我们将在 Inno Setup 脚本中使用 [Setup] 的 AppMutex 属性，以避免 Inno Setup 在 B4X 正在运行时进行 B4X 的安装或卸载，导致旧文件无法被移除等问题。
---
找到了一个示例代码： [Using Named Objects - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/sync/using-named-objects)
> 在 Windows 平台 使 Inno Setup 能够检查 本程序是否正在运行

- Beslyric-for-X.pro
这些文件将被自动复制到输出目录 `OUT_PWD` ，并在之后被打包脚本所使用：
- 图标（ macOS 和 Windows ）；
- 版本信息（仅 Windows ）。
<br>
实现：
- https://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/features/file_copies.prf?id=7227e54445021b8c2ce4f4ab638cc7d43e32a5a7
- https://github.com/qt/qtbase/blob/7227e54445021b8c2ce4f4ab638cc7d43e32a5a7/mkspecs/features/file_copies.prf
Code review ：
- https://codereview.qt-project.org/c/qt/qtbase/+/156784
我从这里找到它：
- https://stackoverflow.com/questions/3984104/qmake-how-to-copy-a-file-to-the-output/54162789#54162789
<br>
又一个 undocumented feature 。
> 使用 file_copies 自动复制所需的文件

- Beslyric-for-X.pro
- README.md
Reverts ce907f965398447ae35e1bf5dde0a2f14161e3fd in #57 .
现在，我对于 qmake 的理解，相比于 #35 那时已经进步许多了，有更好的方式控制 qmake 的行为，所以也就不再需要硬编码目标的输出路径了。
> Revert "使用“ DESTDIR ”变量分离二进制文件"

- Beslyric-for-X.pro
Reverts BesLyric-for-X/BesLyric-for-X#136
由于 [INSTALLS](https://doc.qt.io/qt-5/qmake-variable-reference.html#installs) 的文件的安装位置可由参数 `INSTALL_ROOT` 控制，比 file_copies 更灵活，所以将其撤回，再在之后切换到 INSTALLS 。
同时，这也是为迁移到 CMake 铺路。
> Revert "使用 file_copies 自动复制所需的文件"

- Beslyric-for-X.pro
这两个列表中的文件都会被显示在 Qt Creator 中，但是 `DISTFILES` 中的文件将被用于 `make dist` ， `OTHER_FILES` 则完全不影响 Makefile 。
> 使用 OTHER_FILES 替换 DISTFILES

- Entities/MusicPlayer/musicPlayer.cpp
The symptoms of noise during playback and abnormal high-speed playback will be fixed by 46c78a09f5a4cce6b381ed2e590a921c4d43b49f !
AVCodecContext provides everything we need, but was ignored by us.
See commit message for details.
> Get channel layout and sampling rate of the input audio from AVCodecContext

- BesWidgets/table/BesLListTableView.cpp
BesLListTableView 的 update 只会刷新除了表头外的部分，而直接发送其`Model` 的 `layoutChanged()` 信号则可以刷新包括表头部分的显示
Resolves #159
> fix: 在删除歌词单列表单项时，恰当地更新其布局

- BesWidgets/table/BesLListTableView.cpp
- BesWidgets/table/BesLrcTableView.cpp
- BesWidgets/table/BesNcmSongTableView.cpp
- BesWidgets/table/FinishLrcTableView.cpp
> fix: Hide the `verticalHeader` of all `QTableView`

- BesWidgets/list/BesList.cpp
> fix: 拖动左侧歌词单列表之后，发送`currentRowChanged`消息更新右侧歌词单表项

- BesWidgets/list/BesList.cpp
- BesWidgets/list/BesList.h
- Entities/LyricListManager.cpp
- Entities/LyricListManager.h
- Entities/MP3Editor/AlbumImageHelper.hpp
- Entities/MP3Editor/mp3Editor.pri
- MiddleWidgets/PageLyricList.cpp
- MiddleWidgets/PageLyricList.h
1. 新建继承自 `QRunable` 的 `AlbumImageHelper` 类，用于获取歌词单的歌曲中的第一个有效专辑封面
2. 为每一个歌词单赋值一个全局id，方便异步获取图片后，匹配回对应的歌词单
3. 优化 `BesList` 新增新歌词单列表项的接口 `addItem`, 以支持在构建新项时，传入新的 `id`
4. 歌词单存储结构中，新增 `albumCoverPath` 存储专辑图片的路径
5. 在歌词单项增、删、改，以及拖动改变顺序时，启动线程获取列表从上到下第一个有效歌曲专辑封面
6. 获取新的歌词单封面后，保存数据，并刷新显示图片
+ Resolves #164
> feat: 在歌词单内容发生改变时，获取并更新歌词单封面

- Entities/SkinFactory/ISkin.h
- MiddleWidgets/SettingWidget/SuDonation.cpp
- MiddleWidgets/SettingWidget/SuUpgrade.cpp
- MiddleWidgets/SubPageMaking.cpp
1. 调大所有的 QTabBar 的最小宽度: scaleNum(96) px ->scaleNum(150) px
2. 调大标签 "当前版本号：" 的宽度: 100->150
3. 调大制作歌词页面 "单行编辑" 和 “批量编辑” 标签大小: 75->85
4. 调大下载软件按钮: 100->120
相关 issue: #181
> fix: 调大若干控件尺寸大小，解决部分显示不全问题

- BesWidgets/BesMessageBox.cpp
1. 先前测试的情况只考虑到单行提示的情况，计算宽度时没有测试包含换行符的情况
2. 现在计算宽度时，以 `\n` 为分割符得到多行，以宽度最大的行为文本整体宽度
3. 显示富文本的情况，比如版本更新信息，先转为 plain text，再按第 2 点计算
patch for d224c9f65c8a2308216296edc127f32cf529e31
Resolves #188
> fix: 计算 BesMessageBox 宽度时，考虑多行文本以及富文本的情况

- BesWidgets/list/BesList.cpp
Fix https://github.com/BesLyric-for-X/BesLyric-for-X/pull/179#pullrequestreview-730302318 .
After applying 96949ac42f17352ce022b28f8b11df19f5bfa130 ( #179 ), in PageLyricList, I found a bug with lyricListCreated (the list of user created LyricLists).
When I create a new LyricList:
- If lyricListCreated is empty, it will not display the new LyricList immediately until another LyricList is created.
- If lyricListCreated is not empty, it will not increase its height to fit the number of LyricLists, but keep the previous size and display a vertical scrollbar, regardless of whether its maximum height is really too big to fit in its container (vListLayout). Adding more LyricLists will increase its height, but the total height will be always 1 less than the actual number of LyricLists. For …
> The lyricListCreated list cannot display the newly created LyricList correctly

- BesWidgets/BesScaleUtil.h
We don't like that our application (B4X) is too big to fit into the desktop. The size of the desktop varies, so we should think more about it. The height has already been considered, but the width has not. Thus, I made this PR.
- [HTML Tables generator – TablesGenerator.com](https://www.tablesgenerator.com/html_tables)
All tests are performed on VMware® Workstation 16 Pro 16.1.2 build-17966106 (unlocked).
Like the previous PR, on Windows, I followed [Increasing virtual machine display resolution to a custom resolution beyond the maximum resolution listed in Microsoft Windows (2058577)](https://kb.vmware.com/s/article/2058577) to adjust the resolution. On macOS, I used [MarLoe/VMware.PreferencePane](https://github.com/MarLoe/VMware.PreferencePane) to make resolution adjustment easier. On …
> Also consider the width of the available desktop space before scaling pixels
