BesLyric-for-X/BesLyric-for-X

BesWidgets/BesEditDialog.cpp
BesWidgets/BesEditDialog.h
BesWidgets/BesWidgets.pri
BesWidgets/table/FinishLrcButtonDelegate.cpp
BesWidgets/table/FinishLrcButtonDelegate.h
BesWidgets/table/FinishLrcTableModel.cpp
BesWidgets/table/FinishLrcTableModel.h
BesWidgets/table/FinishLrcTableView.cpp
BesWidgets/table/FinishLrcTableView.h
BottomWidgets/BottomWidget.cpp
Entities/LyricMaker.cpp
Entities/LyricMaker.h
Entities/LyricViewer.h
Entities/MusicPlayer/musicPlayer.cpp
Entities/SkinFactory/ISkin.h
MiddleWidgets/LyricEditorBox.cpp
MiddleWidgets/LyricEditorBox.h
MiddleWidgets/MiddleWidgets.pri
MiddleWidgets/SettingWidget/SuDonation.cpp
MiddleWidgets/SubPageDownloadLyric.cpp
MiddleWidgets/SubPageMaking.cpp
MiddleWidgets/SubPageMaking.h
StackFrame/MainWidget.cpp

增强制作歌词过程中编辑歌词的能力【由网友 Rogue (warkbox) 提供的改进意见】

Edit lyric when making

---

BottomWidgets/BottomWidget.cpp
BottomWidgets/BottomWidget.h

在前面 #15 提交的基础上，补充完善时间进度条的定位 和 时间标签的显示

实现播放条按住不动时更精确地定位；拖动时显示拖动目标时间

---

BesWidgets/BesEditDialog.cpp
BesWidgets/table/BesLListTableView.cpp
BesWidgets/table/BesLrcTableView.cpp
BesWidgets/table/BesNcmSongTableView.cpp
BesWidgets/table/FinishLrcTableView.cpp
BottomWidgets/BottomWidget.cpp
Entities/LyricViewer.h
Entities/MusicPlayer/musicPlayer.cpp
Entities/Phonograph.cpp
MiddleWidgets/LyricEditorBox.cpp
MiddleWidgets/MiddleWidget.cpp
MiddleWidgets/PageLyricList.cpp
MiddleWidgets/PageMain.cpp
MiddleWidgets/PagePreviewLyric.cpp
MiddleWidgets/SettingWidget/SettingScrollPanel.cpp
MiddleWidgets/SettingWidget/SettingWidget.cpp
MiddleWidgets/SettingWidget/SuDonation.cpp
MiddleWidgets/SettingWidget/SuMusicDownload.cpp
MiddleWidgets/SettingWidget/SuUpgrade.cpp
MiddleWidgets/SubPageDownloadLyric.cpp
MiddleWidgets/SubPageDownloadSong.cpp
MiddleWidgets/SubPageMaking.cpp
StackFrame.cpp
StackFrame/AddLyricItemWidget.cpp
StackFrame/MainWidget.cpp
StackFrame/SkinBoxWidget.cpp
Utility/NetAccess.cpp

使用Qt5风格的信号与信号槽语法

---

Entities/MusicPlayer/musicPlayer.cpp

改了个信号连接语法，但暂时没有更多时间了，还请你解决下合并冲突。

Qt5 style patch for 4f6bb8727a4549c24b261465224ebbfc635855de

---

BesWidgets/table/BesLListTableView.h
BesWidgets/table/BesLrcTableView.h
BesWidgets/table/BesNcmSongTableView.h
BesWidgets/table/FinishLrcTableView.h
Define/Struct.h

Delete the itself including.

---

MiddleWidgets/SettingWidget/SuMusicDownload.cpp

将等待下载声明的时间由60s将为30s

---

Entities/LrcProcessor.cpp

修复载入别处来源的LRC歌词乱码问题

---

Beslyric-for-X.pro

在 release 下禁用 qDebug() 的输出

---

MiddleWidgets/SubPageMaking.cpp

修复更改设置自动更新制作歌词页面控件后，默认输出目录实际未生效问题

---

BesWidgets/table/BesNcmSongTableView.cpp
MiddleWidgets/SubPageDownloadLyric.cpp

Reverts BesLyric-for-X/BesLyric-for-X#103

Revert "修复文件名称含有特殊字符时保存失败问题"

---

Beslyric-for-X.pro

Fix https://github.com/BesLyric-for-X/BesLyric-for-X/issues/29 .

限制 Qt 为 5.12.4 及更高版本以使用 OpenSSL 1.1.1

---

main.cpp

Patch for 6bd7eadd2509cce523bdf3998ceeb4e7f23fd949 in #101 .

设置应用名称以使数据文件路径不变

---

Beslyric-for-X.pro

这个说明会显示在下列位置：
- 可执行程序的“属性”页面的“详细信息”选项卡；
- 任务管理器的“详细信息”选项卡的“描述”列；
- Inno Setup 的“正在准备安装”页面。
尽管这个说明通常会被用户忽略，但我们也应该使其内容尽量准确。

重写 Windows 程序的文件说明

---

BesWidgets/BesScaleUtil.h

1368x768
|              | original | modified
| -            | - | -
| list         | ![list-centos_8 2 2004-1368_768-1-GHA](https://user-images.githubusercontent.com/29089388/116020821-9ec69480-a679-11eb-9b43-9ac6911aa4a4.jpg) | ![list-centos_8 2 2004-1368_768-2-proportionally](https://user-images.githubusercontent.com/29089388/116020824-a0905800-a679-11eb-8f0e-57ddf187d0a2.jpg)
| settings end | ![settings_end-centos_8 2 2004-1368_768-1-GHA](https://user-images.githubusercontent.com/29089388/116020829-a128ee80-a679-11eb-8315-e46d73ac2e4a.jpg) | ![settings_end-centos_8 2 2004-1368_768-2-proportionally](https://user-images.githubusercontent.com/29089388/116020830-a1c18500-a679-11eb-8131-91b89397f3bd.jpg)
| update popup | ![update_popup-centos_8 2 …

Scale proportionally when the height of the available screen less than 800 px

---

BesWidgets/BesScaleUtil.h

优化 BesScaleUtil::scale() 中的注释，使其匹配实际行为

---

Entities/LyricViewer.h

1. 改变计算行高的方式: 由预设固定行高调整为累积每一行实际行高
2. 设置每行歌词的显示间隔为一倍的行高
3. 加粗显示当前正在播放的歌词行
Resolves #152

改变计算行高的方式，加粗显示当前播放的歌词行

---

BesWidgets/BesFramelessDialog.cpp
BesWidgets/BesFramelessWidget.cpp

fix: 去除无用的 style sheet 设置

---

BesWidgets/BesWidgets.pri
BesWidgets/table/BesLListTableModel.cpp
BesWidgets/table/BesLListTableModel.h
BesWidgets/table/BesLListTableView.cpp
BesWidgets/table/BesLListTableView.h
BesWidgets/table/BesLListViewStyle.hpp
Entities/AppHelper.h
Entities/LyricListManager.h
MiddleWidgets/PageLyricList.cpp
StackFrame.cpp
StackFrame.h

feat: 实现通过拖动操作对歌词单列表项进行重新排序

---

MiddleWidgets/PageLyricList.cpp

feat: 自动往歌词单“制作历史”里添加歌曲时，默认添加到第一项位置

---

BesWidgets/list/BesList.cpp

fix: 修复在歌词单中将上面的项拖动到下面时，数据插入位置错误问题

---

BesWidgets/list/BesList.cpp
BesWidgets/list/BesList.h
MiddleWidgets/PageLyricList.cpp
MiddleWidgets/PageLyricList.h

Optimize `PageLyricList`

---

MiddleWidgets/SettingWidget/SuDonation.cpp
MiddleWidgets/SettingWidget/SuDonation.h
MiddleWidgets/SettingWidget/SuSoftware.cpp
MiddleWidgets/SettingWidget/SuUpgrade.cpp

1. 将"升级"说明中的 SHA-1 值移动到 "关于本软件" 下
2. 优化 "关于本软件"的描述，新增加群链接和提交 issue 模板链接
3. 将“捐款”改为“打赏”，对打赏的理由进行重新表述，去除不必要的软件下载按钮
Fixes #181

feat: 优化设置页面中的 “升级” 和 "关于本软件"等说明

---

MiddleWidgets/SettingWidget/SuDonation.cpp

patch for commit 54f6df0f07342d3f86bfa2c6aa5e0895738ea900
related PR #183
related issue #181

fix: 纠正不恰当的适用操作系统的描述

---

Entities/MP3Editor/AlbumImageHelper.hpp
Entities/MusicPlayer/musicPlayer.cpp

Related to https://github.com/BesLyric-for-X/BesLyric-for-X/pull/179#pullrequestreview-716935323 . Please see commit message for details.

Directly get byte array from QByteArray by implicit conversion

---

MiddleWidgets/SettingWidget/SuSoftware.cpp

feat: 添加 BesLyric-for-X 使用的图标来源说明

---

.gitmodules
README.md

It's time to do this!
They support Linux x64, macOS x64 and Windows x86, respectively.

Introduce deployment and packaging scripts

---

MiddleWidgets/SettingWidget/SuSoftware.cpp

Fix https://github.com/BesLyric-for-X/BesLyric-for-X/pull/183#discussion_r693509650 .
```diff
- 操作系统: macOS 10.16
+ 操作系统: macOS 10.16 (darwin, 20.2.0, x86_64)
```
```diff
- 操作系统: Ubuntu 20.04.2 LTS
+ 操作系统: Ubuntu 20.04.2 LTS (linux, 5.11.0-27-generic, x86_64)
```
```diff
- 操作系统: Windows 10 Version 2009
+ 操作系统: Windows 10 Version 2009 (winnt, 10.0.19043, x86_64)
```
```diff
- 操作系统: Windows 10 Version 2004
+ 操作系统: Windows 10 Version 2004 (winnt, 10.0.19041, x86_64)
```
```diff
- 操作系统: Windows 8.1 Version 6.3 (Build 9600)
+ 操作系统: Windows 8.1 Version 6.3 (Build 9600) (winnt, 6.3.9600, i386)
```
```diff
- 操作系统: Windows 7 Version 6.1 (Build 7601: SP 1)
+ 操作系统: Windows 7 Version 6.1 (Build 7601: SP 1) (winnt, 6.1.7601, x86_64)
```

Fill in the more accurate OS information in the auto-generated body of GitHub Issues

---

BesWidgets/list/BesList.cpp
BesWidgets/table/BesLListTableView.cpp

template <typename InputIterator> QList::QList(InputIterator first, InputIterator last)
see https://doc.qt.io/qt-5/qlist.html#QList-4

refactor: 避免使用 Qt5.14 才引入的 QList 构造函数（以迭代器为参数）
